#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May  2 15:32:54 2022

@author: chaoliang
"""

import math
from scipy.stats import norm 

def uty(t, y, Bt):
    ret = 0    
    if y >= Bt:
        ret = y
    else:
        aux0 = math.sqrt(math.pi/2/t)*math.exp(-math.pi/4)/norm.cdf(math.sqrt(math.pi/2)) 
        if y*math.sqrt(t) < -35:
            aux = -1/y/math.sqrt(t) * (1-1/y/y/t)/math.sqrt(2*math.pi)
            ret = aux * aux0
        else:
            aux = math.exp(t/2*y*y)*norm.cdf(y*math.sqrt(t))
            ret = aux * aux0
    return ret

K = 6
t = 1
mean = (1+K)/2
std = math.sqrt(35/12)
Bt = math.sqrt(math.pi/2/t)
sum = 0
for i in range(1, K+1):
    sum = sum + uty(t, (i-mean)/std,Bt)

approx = mean + std * sum
def uty(t, y, bt):
    ret = 0    
    if y >= bt:
        ret = y
    else:
        aux0 = math.sqrt(math.pi/2/t)*math.exp(-math.pi/4)/norm.cdf(math.sqrt(math.pi/2)) 
        if y*math.sqrt(t) < -35:
            aux = -1/y/math.sqrt(t) * (1-1/y/y/t)/math.sqrt(2*math.pi)
            ret = aux * aux0
        else:
            aux = math.exp(t/2*y*y)*norm.cdf(y*math.sqrt(t))
            ret = aux * aux0
    return ret

K = 6
t = 1
mean = (1+K)/2
std = math.sqrt(35/12)
Bt = math.sqrt(math.pi/2/t)
sum = 0
for i in range(1, K+1):
    sum = sum + uty(t, (i-mean)/std,Bt)/K

approx = mean + std * sum
